AWSTemplateFormatVersion: '2010-09-09'
Description: KCL Dynamo
Parameters:
  KinesisJournalTableName:
    Description: Description of the CloudWatch alarm
    Type: String
  EventJournalDBName:
    Description: Description of the CloudWatch alarm
    Type: String
  SnapshotDBName:
    Description: Description of the CloudWatch alarm
    Type: String
  StreamName:
    Description: Kinesis stream name
    Type: String

Resources:
  kinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref StreamName
      RetentionPeriodHours: 24
      ShardCount: 1
  kclDynamodb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref KinesisJournalTableName
      AttributeDefinitions:
      - AttributeName: leaseKey
        AttributeType: S
      KeySchema:
      - AttributeName: leaseKey
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  eventJournalDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref EventJournalDBName
      AttributeDefinitions:
      - AttributeName: par
        AttributeType: S
      - AttributeName: num
        AttributeType: N
      KeySchema:
      - AttributeName: par
        KeyType: HASH
      - AttributeName: num
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  snaphshotDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref SnapshotDBName
      AttributeDefinitions:
      - AttributeName: par
        AttributeType: S
      - AttributeName: seq
        AttributeType: N
      - AttributeName: ts
        AttributeType: N
      KeySchema:
      - AttributeName: par
        KeyType: HASH
      - AttributeName: seq
        KeyType: RANGE

      LocalSecondaryIndexes:
        - IndexName: ts-idx
          Projection:
            ProjectionType: ALL
          KeySchema:
          - AttributeName: par
            KeyType: HASH
          - AttributeName: ts
            KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
